### ISSUE TITLE
Give users more granular control over the size of the icon

### ISSUE THREAD

**Issue by hawkinsjon** [mp-strachan/bb-fontawesome#1]
As a user,
I struggle to use this great plugin because I do not have fine control over the size of the icon. 
Often times I find this plugin produces the perfect icon (as compared to the default icon component) although size 1 is too small and size 2 is too large. 

Please allow more granular control of the icon size via CSS or potentially consider allowing decimal values in the size field like shown below:

<img width="307" alt="Screenshot 2023-05-23 at 4 28 44 PM" src="https://github.com/mp-strachan/bb-fontawesome/assets/3512179/6d72b68b-1332-4e80-b3bc-e02a31a47343">

Overall thank you for this plugin, I find myself using it quite often.

**Comment by mp-strachan** [comment]
Thanks for your feedback @hawkinsjon - I will take a look this week at implementing this!

**Comment by hawkinsjon** [comment]
Amazing thank you for your time!

**Comment by mp-strachan** [comment]
Hi @hawkinsjon - I've added a second scale field now, so you have more granular control of the scaling.
I've gone this route to maintain compatibility with existing budibase apps using this plugin.

![image](https://github.com/mp-strachan/bb-fontawesome/assets/26296076/52e6ce9c-0632-47c3-9352-8df756734662)

Sorry it took so long to get this resolved!

**Comment by hawkinsjon** [comment]
Awesome!!! Thank you so much for doing this. Will try it out tonight.

**Comment by mp-strachan** [comment]
I just increased the resolution of the subscale from 0-9 to 0-99 too, so should now have two decimal points of resolution.

**Comment by hawkinsjon** [comment]
Thanks for the subscale addition that's wonderful! Works well.
