### ISSUE TITLE
fa-brands icons

### ISSUE THREAD

**Issue by as000fm** [mp-strachan/bb-fontawesome#2]
Any plans to include the **fa-brands** icons that are part of the free icons? Thank you for your work.

**Comment by mp-strachan** [comment]
Hi @as000fm,

I've just updated the plugin to include the brands as requested. `v1.3_6.4.2` should be the latest version for both free and pro.

Cheers!
Matt

**Comment by as000fm** [comment]
Thank you !!! Envoyé à partir de Courrier pour Windows De : mp-strachanEnvoyé le :1 novembre 2023 21:40À : mp-strachan/bb-fontawesomeCc : as000fm; MentionObjet :Re: [mp-strachan/bb-fontawesome] fa-brands icons (Issue #2) Hi @as000fm,I've just updated the plugin to include the brands as requested. v1.3_6.4.2 should be the latest version for both free and pro.Cheers!Matt—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
